version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
    - 5431:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
    - ore_concentrate_test_pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
    - 8000:8000
    volumes:
    - .:/app

volumes:
  ore_concentrate_test_pgdata:
