"""add date to concentrate

Revision ID: 7ccf63c303ce
Revises: 2e669878e31a
Create Date: 2024-12-28 12:43:04.493105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccf63c303ce'
down_revision: Union[str, None] = '2e669878e31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concentrate', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concentrate', 'date')
    # ### end Alembic commands ###
